[package]
name = "rplc_cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

rplc_core = { path = "../rplc_core" }
clap.workspace = true
miette.workspace = true
anyhow.workspace = true
